#!/usr/bin/env bash
# Start FastjsonExpToolkit Web (backend + frontend). Linux/macOS.
# Backend: uvicorn --reload; Frontend: Next.js HMR.
# Port conflicts: prompt for a free port; always sync frontend via web/.env.local.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUNTIME="$ROOT/.runtime"
LOG_DIR="$RUNTIME/logs"
PID_BACKEND="$RUNTIME/backend.pid"
PID_FRONTEND="$RUNTIME/frontend.pid"
PORTS_FILE="$RUNTIME/ports.env"
WEB_ENV_LOCAL="$ROOT/web/.env.local"
BACKEND_HOST="${BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
ENABLE_RELOAD="${BACKEND_RELOAD:-1}"

mkdir -p "$LOG_DIR"

is_running() {
  local pid_file="$1"
  if [[ -f "$pid_file" ]]; then
    local pid
    pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [[ -n "${pid:-}" ]] && kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
    rm -f "$pid_file"
  fi
  return 1
}

kill_tree() {
  local pid="$1"
  local child
  for child in $(pgrep -P "$pid" 2>/dev/null || true); do
    kill_tree "$child"
  done
  kill "$pid" 2>/dev/null || true
}

stop_pid_file() {
  local name="$1"
  local pid_file="$2"
  if [[ ! -f "$pid_file" ]]; then
    return 0
  fi
  local pid
  pid="$(cat "$pid_file" 2>/dev/null || true)"
  if [[ -n "${pid:-}" ]] && kill -0 "$pid" 2>/dev/null; then
    echo "[*] stopping $name (pid=$pid)"
    kill_tree "$pid"
    for _ in $(seq 1 20); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.1
    done
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
      for child in $(pgrep -P "$pid" 2>/dev/null || true); do
        kill -9 "$child" 2>/dev/null || true
      done
    fi
  fi
  rm -f "$pid_file"
}

port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "sport = :$port" 2>/dev/null | grep -q ":$port"
  elif command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
  else
    ! python -c "import socket;s=socket.socket();s.bind(('127.0.0.1',$port));s.close()" >/dev/null 2>&1
  fi
}

# Resolve a usable port: if busy, ask the user (or require env when non-interactive).
ask_port() {
  local name="$1"
  local port="$2"
  local env_hint="$3"

  if ! port_in_use "$port"; then
    echo "$port"
    return 0
  fi

  echo "[!] $name port :$port is in use" >&2

  if [[ ! -t 0 ]]; then
    echo "    Non-interactive shell — set $env_hint to a free port and re-run." >&2
    return 1
  fi

  local input
  while true; do
    read -r -p "    Enter a free $name port: " input
    if [[ ! "$input" =~ ^[0-9]+$ ]] || (( input < 1 || input > 65535 )); then
      echo "    Invalid port (1-65535)." >&2
      continue
    fi
    if port_in_use "$input"; then
      echo "    :$input is also in use, try another." >&2
      continue
    fi
    echo "$input"
    return 0
  done
}

load_saved_ports() {
  if [[ -f "$PORTS_FILE" ]]; then
    local line key val
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" || "$line" == \#* ]] && continue
      key="${line%%=*}"
      val="${line#*=}"
      case "$key" in
        BACKEND_HOST) BACKEND_HOST="$val" ;;
        BACKEND_PORT) BACKEND_PORT="$val" ;;
        FRONTEND_PORT) FRONTEND_PORT="$val" ;;
      esac
    done <"$PORTS_FILE"
  fi
}

save_ports() {
  cat >"$PORTS_FILE" <<EOF
BACKEND_HOST=$BACKEND_HOST
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
EOF
}

# Next.js reads these at startup (rewrites + client fallback).
write_web_env() {
  local api_origin="http://${BACKEND_HOST}:${BACKEND_PORT}"
  cat >"$WEB_ENV_LOCAL" <<EOF
# Auto-generated by scripts/start.* — do not edit; overwritten on each start.
API_ORIGIN=${api_origin}
NEXT_PUBLIC_API_BASE=${api_origin}
EOF
}

read_web_api_origin() {
  if [[ -f "$WEB_ENV_LOCAL" ]]; then
    grep -E '^API_ORIGIN=' "$WEB_ENV_LOCAL" 2>/dev/null | head -1 | cut -d= -f2- || true
  fi
}

echo "[*] project: $ROOT"

# If a service is already ours, reuse its recorded port.
if is_running "$PID_BACKEND" || is_running "$PID_FRONTEND"; then
  load_saved_ports
fi

if is_running "$PID_BACKEND"; then
  echo "[!] backend already running (:$BACKEND_PORT)"
else
  BACKEND_PORT="$(ask_port "backend" "$BACKEND_PORT" "BACKEND_PORT")"

  if ! command -v fjtoolkit >/dev/null 2>&1 && ! python -c "import fastjson_toolkit" >/dev/null 2>&1; then
    echo "[*] installing Python package (editable)..."
    pip install -e "$ROOT" >/dev/null
  fi
  reload_hint=""
  if [[ "$ENABLE_RELOAD" != "0" ]]; then
    reload_hint=" (auto-reload)"
  fi
  echo "[*] starting backend http://$BACKEND_HOST:$BACKEND_PORT$reload_hint"
  save_ports
  (
    cd "$ROOT" && \
    if [[ "$ENABLE_RELOAD" != "0" ]]; then
      nohup python -m uvicorn fastjson_toolkit.api.app:app \
        --host "$BACKEND_HOST" \
        --port "$BACKEND_PORT" \
        --reload \
        --reload-dir "$ROOT/src" \
        --reload-include '*.py' \
        >"$LOG_DIR/backend.log" 2>&1 &
    else
      nohup python -m uvicorn fastjson_toolkit.api.app:app \
        --host "$BACKEND_HOST" \
        --port "$BACKEND_PORT" \
        >"$LOG_DIR/backend.log" 2>&1 &
    fi
    echo $! >"$PID_BACKEND"
    disown $! 2>/dev/null || true
  )
  ready=0
  for _ in $(seq 1 40); do
    if command -v curl >/dev/null 2>&1; then
      if curl -fsS --connect-timeout 1 --max-time 1 \
        "http://${BACKEND_HOST}:${BACKEND_PORT}/api/health" >/dev/null 2>&1; then
        ready=1
        break
      fi
    fi
    sleep 0.25
  done
  if [[ "$ready" -eq 1 ]]; then
    echo "[+] backend ready"
  else
    echo "[!] backend started but health check timed out — see logs"
  fi
fi

# Always sync frontend → backend port before starting / restarting Next.
api_origin="http://${BACKEND_HOST}:${BACKEND_PORT}"
prev_api_origin="$(read_web_api_origin)"
write_web_env
echo "[*] frontend API_ORIGIN=$api_origin (web/.env.local)"

if is_running "$PID_FRONTEND" && [[ -n "$prev_api_origin" && "$prev_api_origin" != "$api_origin" ]]; then
  echo "[*] backend target changed ($prev_api_origin → $api_origin); restarting frontend"
  stop_pid_file "frontend" "$PID_FRONTEND"
fi

if is_running "$PID_FRONTEND"; then
  echo "[!] frontend already running (:$FRONTEND_PORT)"
else
  FRONTEND_PORT="$(ask_port "frontend" "$FRONTEND_PORT" "FRONTEND_PORT")"
  save_ports

  if [[ ! -d "$ROOT/web/node_modules" ]]; then
    echo "[*] npm install (web)..."
    (cd "$ROOT/web" && npm install)
  fi
  echo "[*] starting frontend http://127.0.0.1:$FRONTEND_PORT (HMR)"
  (
    cd "$ROOT/web" && \
    API_ORIGIN="$api_origin" NEXT_PUBLIC_API_BASE="$api_origin" \
      nohup npm run dev -- --port "$FRONTEND_PORT" \
      >"$LOG_DIR/frontend.log" 2>&1 &
    echo $! >"$PID_FRONTEND"
    disown $! 2>/dev/null || true
  )
fi

save_ports

echo
echo "[+] done"
echo "    Web UI : http://127.0.0.1:$FRONTEND_PORT"
echo "    API    : http://$BACKEND_HOST:$BACKEND_PORT/api/health"
echo "    Docs   : http://$BACKEND_HOST:$BACKEND_PORT/api/docs"
echo "    logs   : $LOG_DIR"
echo "    stop   : ./scripts/stop.sh"
if [[ "$ENABLE_RELOAD" != "0" ]]; then
  echo "    reload : backend watches src/ ; frontend Next.js HMR"
fi
