# Start FastjsonExpToolkit Web (backend + frontend). Windows PowerShell.
# Does NOT start/stop Docker lab.
# Backend: uvicorn --reload; Frontend: Next.js HMR.
# Port conflicts: prompt for a free port; always sync frontend via web/.env.local.
param(
    [switch]$NoPause,
    [switch]$NoReload
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Split-Path -Parent $ScriptDir
$Runtime = Join-Path $Root ".runtime"
$LogDir = Join-Path $Runtime "logs"
$PidBackend = Join-Path $Runtime "backend.pid"
$PidFrontend = Join-Path $Runtime "frontend.pid"
$PortsFile = Join-Path $Runtime "ports.env"
$WebEnvLocal = Join-Path $Root "web\.env.local"
$BackendHost = if ($env:BACKEND_HOST) { $env:BACKEND_HOST } else { "127.0.0.1" }
$BackendPort = if ($env:BACKEND_PORT) { [int]$env:BACKEND_PORT } else { 8000 }
$FrontendPort = if ($env:FRONTEND_PORT) { [int]$env:FRONTEND_PORT } else { 3000 }
$EnableReload = -not $NoReload
if ($env:BACKEND_RELOAD -eq "0") { $EnableReload = $false }

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

function Test-PidRunning([string]$PidFile) {
    if (-not (Test-Path $PidFile)) { return $false }
    $procId = Get-Content $PidFile -ErrorAction SilentlyContinue
    if (-not $procId) { return $false }
    try {
        Get-Process -Id ([int]$procId) -ErrorAction Stop | Out-Null
        return $true
    } catch {
        Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
        return $false
    }
}

function Stop-PidTree([int]$ProcId) {
    Get-CimInstance Win32_Process -Filter "ParentProcessId=$ProcId" -ErrorAction SilentlyContinue |
        ForEach-Object { Stop-PidTree ([int]$_.ProcessId) }
    try {
        Stop-Process -Id $ProcId -Force -ErrorAction SilentlyContinue
    } catch {}
}

function Stop-PidFile([string]$Name, [string]$PidFile) {
    if (-not (Test-Path $PidFile)) { return }
    $procId = Get-Content $PidFile -ErrorAction SilentlyContinue
    if ($procId) {
        try {
            Get-Process -Id ([int]$procId) -ErrorAction Stop | Out-Null
            Write-Host "[*] stopping $Name (pid=$procId)"
            Stop-PidTree ([int]$procId)
        } catch {}
    }
    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
}

function Test-PortInUse([int]$Port) {
    $conn = @(Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue)
    if ($conn.Count -gt 0) { return $true }
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $false
    } catch {
        return $true
    }
}

function Resolve-Port([string]$Name, [int]$Port, [string]$EnvHint) {
    if (-not (Test-PortInUse $Port)) { return $Port }

    Write-Host "[!] $Name port :$Port is in use"
    if ([Console]::IsInputRedirected) {
        throw "Non-interactive shell — set $EnvHint to a free port and re-run."
    }

    while ($true) {
        $entered = Read-Host "    Enter a free $Name port"
        $parsed = 0
        if (-not [int]::TryParse($entered, [ref]$parsed) -or $parsed -lt 1 -or $parsed -gt 65535) {
            Write-Host "    Invalid port (1-65535)."
            continue
        }
        if (Test-PortInUse $parsed) {
            Write-Host "    :$parsed is also in use, try another."
            continue
        }
        return $parsed
    }
}

function Import-SavedPorts {
    if (-not (Test-Path $PortsFile)) { return }
    Get-Content $PortsFile | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $parts = $line.Split("=", 2)
        if ($parts.Count -ne 2) { return }
        switch ($parts[0]) {
            "BACKEND_HOST" { $script:BackendHost = $parts[1] }
            "BACKEND_PORT" { $script:BackendPort = [int]$parts[1] }
            "FRONTEND_PORT" { $script:FrontendPort = [int]$parts[1] }
        }
    }
}

function Save-Ports {
    @"
BACKEND_HOST=$BackendHost
BACKEND_PORT=$BackendPort
FRONTEND_PORT=$FrontendPort
"@ | Set-Content -Path $PortsFile -Encoding ascii
}

function Write-WebEnv {
    $apiOrigin = "http://${BackendHost}:$BackendPort"
    @"
# Auto-generated by scripts/start.* — do not edit; overwritten on each start.
API_ORIGIN=$apiOrigin
NEXT_PUBLIC_API_BASE=$apiOrigin
"@ | Set-Content -Path $WebEnvLocal -Encoding ascii
}

function Read-WebApiOrigin {
    if (-not (Test-Path $WebEnvLocal)) { return "" }
    $line = Get-Content $WebEnvLocal | Where-Object { $_ -match '^API_ORIGIN=' } | Select-Object -First 1
    if (-not $line) { return "" }
    return ($line -split "=", 2)[1]
}

Write-Host "[*] project: $Root"

if ((Test-PidRunning $PidBackend) -or (Test-PidRunning $PidFrontend)) {
    Import-SavedPorts
}

if (Test-PidRunning $PidBackend) {
    Write-Host "[!] backend already running (:$BackendPort)"
} else {
    $BackendPort = Resolve-Port "backend" $BackendPort "BACKEND_PORT"

    $importOk = $false
    try {
        python -c "import fastjson_toolkit" 2>$null
        if ($LASTEXITCODE -eq 0) { $importOk = $true }
    } catch {}
    if (-not $importOk) {
        Write-Host "[*] installing Python package (editable)..."
        pip install -e $Root
    }

    $reloadHint = if ($EnableReload) { " (auto-reload)" } else { "" }
    Write-Host "[*] starting backend http://${BackendHost}:$BackendPort$reloadHint"
    Save-Ports
    $backendOut = Join-Path $LogDir "backend.out.log"
    $backendErr = Join-Path $LogDir "backend.err.log"
    $srcDir = Join-Path $Root "src"
    $args = @(
        "-m", "uvicorn", "fastjson_toolkit.api.app:app",
        "--host", $BackendHost,
        "--port", "$BackendPort"
    )
    if ($EnableReload) {
        $args += @(
            "--reload",
            "--reload-dir", $srcDir,
            "--reload-include", "*.py"
        )
    }
    $proc = Start-Process -FilePath "python" -ArgumentList $args `
        -WorkingDirectory $Root `
        -RedirectStandardOutput $backendOut `
        -RedirectStandardError $backendErr `
        -WindowStyle Hidden `
        -PassThru
    Set-Content -Path $PidBackend -Value $proc.Id -Encoding ascii

    $ready = $false
    for ($i = 0; $i -lt 40; $i++) {
        Start-Sleep -Milliseconds 250
        try {
            $resp = Invoke-WebRequest -Uri "http://${BackendHost}:$BackendPort/api/health" -UseBasicParsing -TimeoutSec 1
            if ($resp.StatusCode -eq 200) { $ready = $true; break }
        } catch {}
    }
    if ($ready) {
        Write-Host "[+] backend ready"
    } else {
        Write-Host "[!] backend started but health check timed out — see logs"
    }
}

# Always sync frontend → backend port before starting / restarting Next.
$apiOrigin = "http://${BackendHost}:$BackendPort"
$prevApiOrigin = Read-WebApiOrigin
Write-WebEnv
Write-Host "[*] frontend API_ORIGIN=$apiOrigin (web/.env.local)"

if ((Test-PidRunning $PidFrontend) -and $prevApiOrigin -and ($prevApiOrigin -ne $apiOrigin)) {
    Write-Host "[*] backend target changed ($prevApiOrigin → $apiOrigin); restarting frontend"
    Stop-PidFile "frontend" $PidFrontend
}

if (Test-PidRunning $PidFrontend) {
    Write-Host "[!] frontend already running (:$FrontendPort)"
} else {
    $FrontendPort = Resolve-Port "frontend" $FrontendPort "FRONTEND_PORT"
    Save-Ports

    $nm = Join-Path $Root "web\node_modules"
    if (-not (Test-Path $nm)) {
        Write-Host "[*] npm install (web)..."
        Push-Location (Join-Path $Root "web")
        try { npm install } finally { Pop-Location }
    }

    Write-Host "[*] starting frontend http://127.0.0.1:$FrontendPort (HMR)"
    $frontendOut = Join-Path $LogDir "frontend.out.log"
    $frontendErr = Join-Path $LogDir "frontend.err.log"
    $webDir = Join-Path $Root "web"
    $npmCmd = if (Get-Command npm.cmd -ErrorAction SilentlyContinue) { "npm.cmd" } else { "npm" }
    $prevEnvApi = $env:API_ORIGIN
    $prevEnvPublic = $env:NEXT_PUBLIC_API_BASE
    $env:API_ORIGIN = $apiOrigin
    $env:NEXT_PUBLIC_API_BASE = $apiOrigin
    try {
        $proc = Start-Process -FilePath $npmCmd -ArgumentList @(
            "run", "dev", "--", "--port", "$FrontendPort"
        ) -WorkingDirectory $webDir -RedirectStandardOutput $frontendOut -RedirectStandardError $frontendErr -WindowStyle Hidden -PassThru
        Set-Content -Path $PidFrontend -Value $proc.Id -Encoding ascii
    } finally {
        if ($null -eq $prevEnvApi) { Remove-Item Env:API_ORIGIN -ErrorAction SilentlyContinue } else { $env:API_ORIGIN = $prevEnvApi }
        if ($null -eq $prevEnvPublic) { Remove-Item Env:NEXT_PUBLIC_API_BASE -ErrorAction SilentlyContinue } else { $env:NEXT_PUBLIC_API_BASE = $prevEnvPublic }
    }
}

Save-Ports

Write-Host ""
Write-Host "[+] done"
Write-Host "    Web UI : http://127.0.0.1:$FrontendPort"
Write-Host "    API    : http://${BackendHost}:$BackendPort/api/health"
Write-Host "    Docs   : http://${BackendHost}:$BackendPort/api/docs"
Write-Host "    logs   : $LogDir"
Write-Host "    stop   : .\scripts\stop.ps1  or  .\scripts\stop.bat"
if ($EnableReload) {
    Write-Host "    reload : backend watches src/ ; frontend Next.js HMR"
}

if (-not $NoPause) {
    Write-Host ""
    Write-Host "Press any key to close..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
}
